export const SET_POKEMONS = "SET_POKEMONS";
export const SET_LOADING = "SET_LOADING";
export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const INCREASE_COUNTER_ASYNC = "INCREASE_COUNTER_ASYNC";
